// <auto-generated />
using System;
using EMigrant.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMigrant.App.Persistencia.Migrations
{
    [DbContext(typeof(Conexion))]
    [Migration("20211127145153_AvancesV8")]
    partial class AvancesV8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EMigrant.App.Dominio.Alimentacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Alimentacion");
                });

            modelBuilder.Entity("EMigrant.App.Dominio.AlojoPermanente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("AlojoPermanente");
                });

            modelBuilder.Entity("EMigrant.App.Dominio.AlojoTemporal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("AlojoTemporal");
                });

            modelBuilder.Entity("EMigrant.App.Dominio.AyudaLegal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("AyudaLegal");
                });

            modelBuilder.Entity("EMigrant.App.Dominio.Educacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Educacion");
                });

            modelBuilder.Entity("EMigrant.App.Dominio.Empleo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Empleo");
                });

            modelBuilder.Entity("EMigrant.App.Dominio.Institucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PagWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoServicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instituciones");
                });

            modelBuilder.Entity("EMigrant.App.Dominio.Salud", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioridadNecesidades")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Salud");
                });

            modelBuilder.Entity("EMigrant.App.Dominio.migrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Alimentacionid")
                        .HasColumnType("int");

                    b.Property<int?>("AlojoPermanenteid")
                        .HasColumnType("int");

                    b.Property<int?>("AlojoTemporalid")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AyudaLegalid")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Educacionid")
                        .HasColumnType("int");

                    b.Property<int?>("Empleoid")
                        .HasColumnType("int");

                    b.Property<DateTime>("FNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Saludid")
                        .HasColumnType("int");

                    b.Property<int>("SituacionLaboral")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Alimentacionid");

                    b.HasIndex("AlojoPermanenteid");

                    b.HasIndex("AlojoTemporalid");

                    b.HasIndex("AyudaLegalid");

                    b.HasIndex("Educacionid");

                    b.HasIndex("Empleoid");

                    b.HasIndex("Saludid");

                    b.ToTable("migrantes");
                });

            modelBuilder.Entity("EMigrant.App.Dominio.migrante", b =>
                {
                    b.HasOne("EMigrant.App.Dominio.Alimentacion", "Alimentacion")
                        .WithMany()
                        .HasForeignKey("Alimentacionid");

                    b.HasOne("EMigrant.App.Dominio.AlojoPermanente", "AlojoPermanente")
                        .WithMany()
                        .HasForeignKey("AlojoPermanenteid");

                    b.HasOne("EMigrant.App.Dominio.AlojoTemporal", "AlojoTemporal")
                        .WithMany()
                        .HasForeignKey("AlojoTemporalid");

                    b.HasOne("EMigrant.App.Dominio.AyudaLegal", "AyudaLegal")
                        .WithMany()
                        .HasForeignKey("AyudaLegalid");

                    b.HasOne("EMigrant.App.Dominio.Educacion", "Educacion")
                        .WithMany()
                        .HasForeignKey("Educacionid");

                    b.HasOne("EMigrant.App.Dominio.Empleo", "Empleo")
                        .WithMany()
                        .HasForeignKey("Empleoid");

                    b.HasOne("EMigrant.App.Dominio.Salud", "Salud")
                        .WithMany()
                        .HasForeignKey("Saludid");

                    b.Navigation("Alimentacion");

                    b.Navigation("AlojoPermanente");

                    b.Navigation("AlojoTemporal");

                    b.Navigation("AyudaLegal");

                    b.Navigation("Educacion");

                    b.Navigation("Empleo");

                    b.Navigation("Salud");
                });
#pragma warning restore 612, 618
        }
    }
}
